# Waveguide physical parameters:
# NB: EITHER a fixed core width OR core height is specified here
#     while the other core dimension is the free parameter in the solution
#	  (supplying both keys will generate an error).
#     The mode solver data for the core dimension free parameter
#     used for fitting are supplied in the "geom" keys below.
[wg]
core_width = 0.7						# Fixed waveguide core width (um)
#core_height = 0.2						# Fixed waveguide core height (um)
lambda_resonance = 0.532				# Ring resonance wavelength (um)
n_clad = 1.33                           # Cladding refractive index
n_core = 1.49                           # Core refractive index
n_sub = 1.2                             # Substrate refractive index
ni_op_point = 1.00e-6					# Fluid refractive index imaginary component operating point (RIU, defautl = 1e-6)
roughness_lc = 50e-9                    # Vertical sidewall roughness auto-correlation length (nm, default = 50 nm)
roughness_sigma = 6e-9                  # Vertical sidewall roughness standard deviation (nm, defautl = 6 nm)
polarization = "TE"						# Mode polarization, for use in graph labeling ("TM" or "TE, default = "TE")

# Ring parameters
[ring]
coupling_length = 0                     # Bus/ring coupling lenght in a racetrack (default = 0 for a circular ring)

# Spiral physical parameters:
[spiral]
spacing = 5								# Spacing between the waveguides in the spiral (um, default = 5.0)
turns_min = 0.5							# Minimum allowed turns in the spiral (default = 0.5)
turns_max = 50							# Maximum number of allowed turns in the spiral in the optimization (default = 25)

# Model fitting parameters:
[fit]
gamma_order = 4							# Polynomial model order for gamma(h) interpolation (default = 4)
neff_order = 3							# Polynomial model order for neff(h) interpolation (default = 3)
alpha_wg_order = 4						# Polynomial model order for alpha_wg(h) interpolation (default = 3)
optimization_method = "SLSQP"			# scipy.optimize.minimize() "method" parameter used for S(u, r) minimization (default = "SLSQP")

# Analysis limit parameters:
[limits]
r_min = 10								# Analysis domain minimum radius (um)
r_max = 10000							# Analysis domain maximum radius (um)
r_samples_per_decade = 50				# Analysis domain  logarithmic sampling rate (number of samples per decade, default = 50)
alpha_bend_threshold = 0.01				# Maximum value of alpha_bend (db/cm) for h search domain lower bound in optimization (default = 0.01 dB)
min_delta_ni = 1.0e-6					# Desired minimum resolvable change in ni (RIU, default = 1e-6)
T_SNR = 20								# Transmission measurement SNR (dB, default = 20)

# Graphing and file I/O and parameters:
[io]
draw_largest_spiral = true				# Enable/disable drawing of largest spiral (default = true)
map2D_colormap = "plasma"				# matplotlib colormap for rendering 2D images (default = "viridis")
map2D_n_grid_points = 500				# Number of samples along an axis in the 2D maps (default = 500)
map2D_overlay_color_dark = "white"		# color for overlay plots on "mainly dark" 2D maps (default = "white")
map2D_overlay_color_light = "white"		# color for overlay plots on "mainly light" 2D maps (default = "white")
map_line_profiles = [20, 45, 65, 75]	# gamma values for line profiles in 2D maps (default = [])
output_sub_dir = "data"					# Subdirectory in which to write files, relative (default = "", use "/" or "\\" for delimiters on Windows)
write_2D_maps = true					# Enable/disable writing of MRR result 2D maps (default = true)
write_excel_files = true				# Enable/disable writing of results to Excel files (default = true)
write_spiral_sequence_to_file = true	# Enable/disable writing of spiral sequence to TIFF multi-image file (default = true)

# Debugging flags:
[debug]
disable_R_domain_check = true			# Show warning if the mode solver data doesn't adequately cover analysis domain, see below (boolean, default = false)
models_only = false						# Calculate and plot models only, without analysing the waveguides (boolean, default = false)
analyze_spiral = true					# Analyse the MRR and linear waveguides only (boolean, default = True)

#
# Mode solver solution data as a function of the waveguide geometry free parameter (u):
# - u (um): EITHER the core height or width, depending on which of "core_width"
#           OR "core_height" was specified in the "wg" section
# - gamma ([0..1]): normalized proportion of mode power in the cladding
# - neff: fundamental mode effectve index
# - r (um): list of radii at which the bending losses are specified (um)
# - alpha_bend (dB/um): list of corresponding radiative bending losses
#
# NB: The dctionary keys for each value of "u" must be of the form "geom.X",
#     where X is any user-defined index (the simplest is just to use 1, 2, 3, ...)

[geom.1]
u = 0.145
gamma = 0.75
neff = 1.33107
r = [1165.0, 2104.5, 3044.0, 3983.5, 4923.0, 5862.5, 6802.0, 7741.5, 8681.0, 9620.5,
    10560.0, 11499.5,]
alpha_bend = [1.0304e-3, 3.4774e-4, 1.4213e-4, 5.8959e-5, 2.4398e-5, 1.0100e-5,
    4.1611e-6, 1.6752e-6, 6.5156e-7, 2.4908e-7, 9.9347e-8, 4.6051e-8,]

[geom.2]
u = 0.16
gamma = 0.65
neff = 1.33382
r = [182.0, 373.5, 565.0, 756.5, 948.0, 1139.5, 1331.0, 1522.5, 1714.0, 1905.5, 2097.0,
    2288.5,]
alpha_bend =[5.4177e-3, 9.9925e-4, 2.5506e-4, 7.5502e-5, 2.4853e-5, 8.7246e-6,
    3.1376e-6, 1.2135e-6, 4.8917e-7, 1.8141e-7, 5.6059e-8, 1.3463e-8,]

[geom.3]
u = 0.2
gamma = 0.45
neff = 1.34742
r = [37.4, 56.7, 76.0, 95.3, 114.6, 133.9, 153.2, 172.5, 191.8, 211.1, 230.4, 249.7,]
alpha_bend = [1.2424e-2, 3.2789e-3, 1.0600e-3, 3.4414e-4, 1.1649e-4, 4.0575e-5,
    1.4447e-5, 5.2353e-6, 1.9248e-6, 7.1622e-7, 2.6926e-7, 1.0213e-7,]

[geom.4]
u = 0.23
gamma = 0.36
neff = 1.35833
r = [26.0, 35.5, 45.0, 54.5, 64.0, 73.5, 83.0, 92.5, 102.0, 111.5, 121.0, 130.5,]
alpha_bend = [1.0976e-2, 3.3012e-3, 1.0600e-3, 3.5437e-4, 1.2166e-4, 4.2660e-5,
    1.5217e-5, 5.5054e-6, 2.0158e-6, 7.4563e-7, 2.7822e-7, 1.0461e-7,]

[geom.5]
u = 0.26
gamma = 0.3
neff = 1.36873
r = [20.0, 26.0, 32.0, 38.0, 44.0, 50.0, 56.0, 62.0, 68.0, 74.0, 80.0, 86.0,]
alpha_bend = [1.0821e-2, 3.5041e-3, 1.0900e-3, 3.7037e-4, 1.2869e-4, 4.5464e-5,
    1.6289e-5, 5.9067e-6, 2.1639e-6, 7.9983e-7, 2.9792e-7, 1.1173e-7,]

[geom.6]
u = 0.3
gamma = 0.24
neff = 1.37983
r = [16.0, 20.0, 24.0, 28.0, 32.0, 36.0, 40.0, 44.0, 48.0, 52.0, 56.0, 60.0,]
alpha_bend = [1.0178e-2, 3.5043e-3, 1.2300e-3, 4.4228e-4, 1.6086e-4,  5.9237e-5,
    2.2055e-5, 8.2909e-6, 3.1434e-6, 1.2007e-6, 4.6170e-7, 1.7858e-7,]

[geom.7]
u = 0.35
gamma = 0.2
neff = 1.39409
r = [13.0, 16.0, 19.0, 22.0, 25.0, 28.0, 31.0, 34.0, 37.0, 40.0, 43.0, 46.0,]
alpha_bend = [1.0810e-2, 3.7140e-3, 1.0200e-3, 3.4313e-4, 1.1652e-4, 3.9965e-5,
    1.3836e-5, 4.8301e-6, 1.6991e-6, 6.0172e-7, 2.1438e-7, 7.6790e-8,]

[geom.8]
u = 0.4
gamma = 0.16
neff = 1.40789
r = [9.9, 12.4, 14.9, 17.4, 19.9, 22.4, 24.9, 27.4, 29.9, 32.4, 34.9, 37.4, 39.9,]
alpha_bend = [2.1018e-2, 7.1039e-3, 2.4227e-3, 8.3171e-4, 2.8757e-4, 1.0021e-4,
    3.5194e-5, 1.2453e-5, 4.4373e-6, 1.5912e-6, 5.7390e-7, 2.0808e-7, 7.5797e-8,]
