# Waveguide physical parameters:
# NB: EITHER a fixed core width OR core height is specified here
#     while the other core dimension is the free parameter in the solution
#	  (supplying both keys will generate an error).
#     The mode solver data for the core dimension free parameter
#     used for fitting are supplied in the "geom" keys below.
[wg]
core_width = 0.7						# Fixed waveguide core width (um)
#core_height = 0.2						# Fixed waveguide core height (um)
lambda_resonance = 0.532				# Ring resonance wavelength (um)
ni_op_point = 1.00e-6					# Fluid refractive index imaginary component operating point (RIU)
n_clad = 1.33                           # Cladding refractive index
n_core = 1.49                           # Core refractive index
n_sub = 1.2                             # Substrate refractive index
roughness_lc = 50e-9                    # Vertical sidewall roughness auto-correlation length (nm, default = 50 nm)
roughness_sigma = 6e-9                  # Vertical sidewall roughness standard deviation (nm, defautl = 10 nm)
polarization = "TE"						# Mode polarization, for use in graph labeling ("TM" or "TE, default = "TE")

# Ring parameters
[ring]
coupling_length = 0                     # Bus/ring coupling lenght in a racetrack (default = 0 for a circular ring)

# Spiral physical parameters:
[spiral]
spacing = 5								# Spacing between the waveguides in the spiral (um)
turns_min = 0.5							# Minimum allowed turns in the spiral (default = 0.5)
turns_max = 50							# Maximum number of allowed turns in the spiral in the optimization (default = 25)

# Model fitting parameters:
[fit]
gamma_order = 4							# Polynomial model order for interpolating gamma(h)
neff_order = 3							# Polynomial model order for interpolating neff(h)
alpha_wg_order = 4						# Polynomial model order for interpolating alpha_wg(h)
optimization_method = "SLSQP"			# scipy.optimize.minimize() "method" parameter, used for estimation of maximum achievable sensitivity at each radius (default = "SLSQP")

# Analysis limit parameters:
[limits]
alpha_bend_threshold = 0.01				# Maximum value of alpha_bend (db/cm) for h search domain lower bound in optimization (default = 0.01 dB)
min_delta_ni = 1.0e-6					# Desired minimum resolvable change in ni (RIU)
r_min = 10								# Analysis domain minimum radius (um)
r_max = 10000							# Analysis domain maximum radius (um)
r_samples_per_decade = 50				# Analysis domain  logarithmic sampling rate (number of samples per decade)
T_SNR = 20								# Transmission measurement SNR (dB)

# Graphing and file I/O and parameters:
[io]
draw_largest_spiral = true				# Enable/disable drawing of largest spiral (default = true)
map2D_colormap = "plasma"				# matplotlib colormap for rendering 2D images (default = "viridis")
map2D_n_grid_points = 500				# Number of samples along an axis in the 2D maps (default = 500)
map2D_overlay_color_dark = "white"		# color for overlay plots on "mainly dark" 2D maps (default = "white")
map2D_overlay_color_light = "white"		# color for overlay plots on "mainly light" 2D maps (default = "black")
map_line_profiles = [20, 45, 65, 75]	# gamma values for line profiles in 2D maps (default = [])
output_sub_dir = "data"					# Subdirectory in which to write files, relative (default = "", use "/" or "\\" for delimiters on Windows)
write_2D_maps = true					# Enable/disable writing of MRR result 2D maps (default = true)
write_excel_files = true				# Enable/disable writing of results to Excel files (default = true)
write_spiral_sequence_to_file = true	# Enable/disable writing of spiral sequence to TIFF multi-image file (default = true)

# Debugging flags:
[debug]
disable_R_domain_check = true			# Show warning but don't exit if the mode solver data doesn't adequately cover analysis domain, see below (boolean, default = false)
models_only = false						# Calculate and plot models only, without analysing the waveguides (boolean, default = false)
analyze_spiral = true					# Analyse the MRR and linear waveguides only (boolean, default = True)

#
# Mode solver solution data as a function of waveguide geometry free parameter (u):
# - u: either the core height or width in um, depending on which of "core_width" OR "core_height" was specified in the "wg" section
# - gamma: normalized proportion of mode power in the cladding
# - r: list of readii at which the bending losses are specified
# - alpha_bend: list of corresponding bending losses (dB/90o)

[geom.1]
u = 0.145
gamma = 0.75
neff = 1.33107
r = [ 1165.0, 2104.5, 3044.0, 3983.5, 4923.0, 5862.5, 6802.0, 7741.5, 8681.0, 9620.5, 10560.0, 11499.5,]
alpha_bend = [ 0.0010304307885333202, 0.00034774158464642225, 0.0001421269903342805, 5.895926025611426e-5, 2.439817220861968e-5, 1.0100048947931964e-5, 4.161148949862471e-6, 1.6751645850240153e-6, 6.515564037164926e-7, 2.490792304697348e-7, 9.934696254625115e-8, 4.605065576148408e-8,]

[geom.2]
u = 0.160
gamma = 0.65
neff = 1.33382
r = [ 182.0, 373.5, 565.0, 756.5, 948.0, 1139.5, 1331.0, 1522.5, 1714.0, 1905.5, 2097.0, 2288.5,]
alpha_bend = [ 0.005417677461795471, 0.0009992512201689023, 0.0002550578704559528, 7.550197706673706e-5, 2.4853106572488692e-5, 8.724568097075875e-6, 3.137637575944408e-6, 1.2135120652745127e-6, 4.891748116201867e-7, 1.8140935144215714e-7, 5.6059005122131435e-8, 1.3462944818405722e-8,]

[geom.3]
u = 0.200
gamma = 0.45
neff = 1.34742
r = [ 37.4, 56.7, 76.0, 95.3, 114.6, 133.9, 153.2, 172.5, 191.8, 211.1, 230.4, 249.7,]
alpha_bend = [ 0.012423644, 0.003278896, 0.00106, 0.000344135, 0.00011649, 4.05746e-5, 1.44469e-5, 5.2353e-6, 1.92476e-6, 7.16219e-7, 2.69264e-7, 1.02132e-7,]

[geom.4]
u = 0.230
gamma = 0.36
neff = 1.35833
r = [ 26.0, 35.5, 45.0, 54.5, 64.0, 73.5, 83.0, 92.5, 102.0, 111.5, 121.0, 130.5,]
alpha_bend = [ 0.010975978, 0.003301191, 0.00106, 0.000354373, 0.000121661, 4.26599e-5, 1.52168e-5, 5.50544e-6, 2.01582e-6, 7.45634e-7, 2.78224e-7, 1.04605e-7,]

[geom.5]
u = 0.260
gamma = 0.3
neff = 1.36873
r = [ 20.0, 26.0, 32.0, 38.0, 44.0, 50.0, 56.0, 62.0, 68.0, 74.0, 80.0, 86.0,]
alpha_bend = [ 0.010820873, 0.003504094, 0.00109, 0.000370372, 0.000128686, 4.54643e-5, 1.62894e-5, 5.90669e-6, 2.16392e-6, 7.99826e-7, 2.97923e-7, 1.11725e-7,]

[geom.6]
u = 0.300
gamma = 0.24
neff = 1.37983
r = [ 16.0, 20.0, 24.0, 28.0, 32.0, 36.0, 40.0, 44.0, 48.0, 52.0, 56.0, 60.0,]
alpha_bend = [ 0.0101780103, 0.003504338, 0.00123, 0.000442279, 0.000160857, 5.92368e-5, 2.20547e-5, 8.29093e-6, 3.14337e-6, 1.20072e-6, 4.61701e-7, 1.7858e-7,]

[geom.7]
u = 0.350
gamma = 0.2
neff = 1.39409
r = [ 13.0, 16.0, 19.0, 22.0, 25.0, 28.0, 31.0, 34.0, 37.0, 40.0, 43.0, 46.0,]
alpha_bend = [ 0.0108100502, 0.0037139705, 0.00102, 0.000343129, 0.000116518, 3.99651e-5, 1.38357e-5, 4.83015e-6, 1.6991e-6, 6.01722e-7, 2.14379e-7, 7.679e-8,]

[geom.8]
u = 0.400
gamma = 0.16
neff = 1.40789
r = [ 9.9, 12.4, 14.9, 17.4, 19.9, 22.4, 24.9, 27.4, 29.9, 32.4, 34.9, 37.4, 39.9,]
alpha_bend = [ 0.021017888333175708, 0.007103917457313029, 0.0024226611169341733, 0.0008317136812009603, 0.00028757340119389685, 0.00010021328346364666, 3.519448966466404e-5, 1.2453324560936106e-5, 4.437342878280444e-6, 1.5912087422105235e-6, 5.739048725286092e-7, 2.0807509947516436e-7, 7.579674411417103e-8,]
